services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5015:5015"
    env_file:
      - ./api-gateway/.env
    restart: unless-stopped
    networks:
      - medisphere-network

  admin-service:
    build: ./services/admin-service
    ports:
      - "5008:5008"
    env_file:
      - ./services/admin-service/.env
    restart: unless-stopped
    networks:
      - medisphere-network
    depends_on:
      - api-gateway

  appointment-service:
    build: ./services/appointment-service
    ports:
      - "5002:5002"
    env_file:
      - ./services/appointment-service/.env
    restart: unless-stopped
    networks:
      - medisphere-network
    depends_on:
      - api-gateway

  auth-service:
    build: ./services/auth-service
    ports:
      - "5006:5006"
    env_file:
      - ./services/auth-service/.env
    restart: unless-stopped
    networks:
      - medisphere-network
    depends_on:
      - api-gateway

  doctor-service:
    build: ./services/doctor-service
    ports:
      - "6010:6010"
    env_file:
      - ./services/doctor-service/.env
    restart: unless-stopped
    networks:
      - medisphere-network
    depends_on:
      - api-gateway

  notification-service:
    build: ./services/notification-service
    ports:
      - "6002:6002"
    env_file:
      - ./services/notification-service/.env
    restart: unless-stopped
    networks:
      - medisphere-network
    depends_on:
      - api-gateway

  patient-service:
    build: ./services/patient-service
    ports:
      - "5005:5005"
    env_file:
      - ./services/patient-service/.env
    restart: unless-stopped
    networks:
      - medisphere-network
    depends_on:
      - api-gateway

  payment-service:
    build: ./services/payment-service
    ports:
      - "5003:5003"
    env_file:
      - ./services/payment-service/.env
    restart: unless-stopped
    networks:
      - medisphere-network
    depends_on:
      - api-gateway

  telemedicine-service:
    build: ./services/telemedicine-service
    ports:
      - "6001:6001"
    env_file:
      - ./services/telemedicine-service/.env
    restart: unless-stopped
    networks:
      - medisphere-network
    depends_on:
      - api-gateway

  frontend:
    build: ./services/frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - medisphere-network

networks:
  medisphere-network:
    driver: bridge