import jsPDF from "jspdf";

const getDoctorName = (prescription) => {
  if (typeof prescription?.doctorId === "object" && prescription?.doctorId?.fullName) {
    return prescription.doctorId.fullName;
  }

  return prescription?.doctorName || "Dr. Unknown";
};

const getPatientName = (prescription) => {
  return prescription?.patientName || "Unknown Patient";
};

const getAppointmentId = (prescription) => {
  if (typeof prescription?.appointmentId === "object" && prescription?.appointmentId?._id) {
    return prescription.appointmentId._id;
  }

  return prescription?.appointmentId || "N/A";
};

const getIssuedDate = (prescription) => {
  const rawDate = prescription?.issuedDate || prescription?.createdAt;

  if (!rawDate) return "N/A";

  const parsedDate = new Date(rawDate);

  if (Number.isNaN(parsedDate.getTime())) {
    return rawDate;
  }

  return parsedDate.toLocaleDateString("en-CA");
};

const addWrappedText = (doc, text, x, y, maxWidth, lineHeight = 7) => {
  const lines = doc.splitTextToSize(text || "", maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
};

const downloadPrescriptionPdf = (prescription) => {
  const doc = new jsPDF();

  doc.setFillColor(29, 45, 68);
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("MEDISPHERE PRESCRIPTION REPORT", 14, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Professional Digital Prescription Summary", 14, 24);

  doc.setTextColor(29, 45, 68);
  doc.setDrawColor(199, 217, 229);
  doc.setLineWidth(0.5);

  doc.roundedRect(14, 38, 182, 30, 4, 4);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Prescription Overview", 18, 46);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Doctor: ${getDoctorName(prescription)}`, 18, 54);
  doc.text(`Patient: ${getPatientName(prescription)}`, 110, 54);
  doc.text(`Appointment ID: ${String(getAppointmentId(prescription))}`, 18, 61);
  doc.text(`Issued Date: ${getIssuedDate(prescription)}`, 110, 61);

  let currentY = 80;

  doc.roundedRect(14, currentY, 182, 28, 4, 4);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Diagnosis", 18, currentY + 8);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  currentY = addWrappedText(
    doc,
    prescription?.diagnosis || "No diagnosis available",
    18,
    currentY + 16,
    172
  ) + 8;

  doc.roundedRect(14, currentY, 182, 28, 4, 4);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Clinical Notes", 18, currentY + 8);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  currentY = addWrappedText(
    doc,
    prescription?.notes || "No additional notes available",
    18,
    currentY + 16,
    172
  ) + 8;

  doc.roundedRect(14, currentY, 182, 14, 4, 4);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Prescribed Medicines", 18, currentY + 9);

  currentY += 20;

  const medicines = prescription?.medicines || [];

  if (medicines.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("No medicine records available.", 18, currentY);
    currentY += 10;
  } else {
    medicines.forEach((medicine, index) => {
      if (currentY > 250) {
        doc.addPage();
        currentY = 20;
      }

      doc.setDrawColor(220, 225, 230);
      doc.roundedRect(14, currentY, 182, 28, 4, 4);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text(`${index + 1}. ${medicine.medicineName || "Medicine"}`, 18, currentY + 8);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`Dosage: ${medicine.dosage || "N/A"}`, 18, currentY + 15);
      doc.text(`Frequency: ${medicine.frequency || "N/A"}`, 80, currentY + 15);
      doc.text(`Duration: ${medicine.duration || "N/A"}`, 145, currentY + 15);

      const instructions = medicine.instructions || "No special instructions";
      currentY = addWrappedText(doc, `Instructions: ${instructions}`, 18, currentY + 22, 172, 5) + 6;
    });
  }

  if (currentY > 255) {
    doc.addPage();
    currentY = 20;
  }

  doc.setDrawColor(180, 190, 205);
  doc.line(14, currentY + 8, 196, currentY + 8);

  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(90, 100, 115);
  doc.text(
    "This prescription was digitally generated by Medisphere.",
    14,
    currentY + 16
  );

  const fileName = `${getPatientName(prescription)
    .replace(/\s+/g, "_")
    .toLowerCase()}_prescription_report.pdf`;

  doc.save(fileName);
};

export { downloadPrescriptionPdf };